[package]
name = "durian-cheat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
process-memory = "0.5.0"
sysinfo = "0.20.3"
mach = "0.3.2"
libc = "0.2.147"